### ISSUE TITLE
Fails to start due to tensorflow issue - even when TPU commented out

### ISSUE THREAD

**Issue by och29** [bezineb5/RoboScan#54]
```
[+] Running 4/0
 ✔ Container docker-samba-1     Created                                                                                                                                                                    0.0s 
 ✔ Container docker-rsyncd-1    Created                                                                                                                                                                    0.0s 
 ✔ Container docker-roboscan-1  Created                                                                                                                                                                    0.0s 
 ✔ Container docker-frontend-1  Created                                                                                                                                                                    0.0s 
Attaching to docker-frontend-1, docker-roboscan-1, docker-rsyncd-1, docker-samba-1
docker-rsyncd-1    | 2024/01/21 18:01:07 [1] rsyncd version 3.2.7 starting, listening on port 873
docker-samba-1     | smbd version 4.13.7 started.
docker-samba-1     | Copyright Andrew Tridgell and the Samba Team 1992-2020
docker-samba-1     | daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
docker-frontend-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
docker-frontend-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
docker-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
docker-frontend-1  | 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
docker-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
docker-frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
docker-frontend-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
docker-roboscan-1  | Traceback (most recent call last):
docker-roboscan-1  |   File "/app/scanner/object_detection.py", line 9, in <module>
docker-roboscan-1  |     from tensorflow import lite as tflite # First, try tensorflow
docker-roboscan-1  | ModuleNotFoundError: No module named 'tensorflow'
docker-roboscan-1  | 
docker-roboscan-1  | During handling of the above exception, another exception occurred:
docker-roboscan-1  | 
docker-roboscan-1  | Traceback (most recent call last):
docker-roboscan-1  |   File "/app/webapp.py", line 16, in <module>
docker-roboscan-1  |     from scanner import detector_scanner
docker-roboscan-1  |   File "/app/scanner/detector_scanner.py", line 9, in <module>
docker-roboscan-1  |     from scanner.object_detection import ObjectDetection
docker-roboscan-1  |   File "/app/scanner/object_detection.py", line 11, in <module>
docker-roboscan-1  |     import tflite_runtime.interpreter as tflite # TensorFlow lite interpreter
docker-roboscan-1  |   File "/usr/local/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 41, in <module>
docker-roboscan-1  |     from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
docker-roboscan-1  | ImportError: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/python3.9/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.cpython-39-aarch64-linux-gnu.so)
docker-roboscan-1 exited with code 0
```

**Comment by och29** [comment]
I've also tried running this in a VSCode docker environment and I'm still getting errors although this time:

```
2024-01-29T16:16:52.863733238Z   File "/app/webapp.py", line 10, in <module>
2024-01-29T16:16:52.863780330Z     from flask_restx import Api, Resource, fields
2024-01-29T16:16:52.863797570Z   File "/usr/local/lib/python3.9/site-packages/flask_restx/__init__.py", line 5, in <module>
2024-01-29T16:16:52.863814163Z     from .api import Api  # noqa
2024-01-29T16:16:52.863828922Z   File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 50, in <module>
2024-01-29T16:16:52.863844274Z     from .swagger import Swagger
2024-01-29T16:16:52.863859329Z   File "/usr/local/lib/python3.9/site-packages/flask_restx/swagger.py", line 18, in <module>
2024-01-29T16:16:52.863874366Z     from werkzeug.routing import parse_rule
2024-01-29T16:16:52.863888569Z ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/usr/local/lib/python3.9/site-packages/werkzeug/routing/__init__.py)
```

Sorry to at you @bezineb5 but I'm not sure where to head with this

**Comment by bezineb5** [comment]
Sorry, I didn't see your question earlier. It looks like some libraries have been updated, which were not properly pinned. I'll have a look at it.

**Comment by bezineb5** [comment]
@och29 - I made an update which should fix your 2 issues. Thanks for reporting!
